spring:
  datasource:
    url: jdbc:mysql://localhost/sb-microservices-db
    username: saikat
    password: saikat
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
