spring:
  datasource:
    url: jdbc:mysql://localhost/sb-microservices-db
    username: saikat
    password: saikat
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka


