server:
  port: 8082

spring:
  datasource:
    username: saikat
    password: saikat
    url: jdbc:mysql://localhost/SB_Microservice_DB

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

management:
  tracing:
    sampling:
      probability: 1.0